/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq.tables;


import com.neoin.shop.jooq.DefaultSchema;
import com.neoin.shop.jooq.Keys;
import com.neoin.shop.jooq.tables.records.VendorGroupRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorGroup extends TableImpl<VendorGroupRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>vendor_group</code>
     */
    public static final VendorGroup VENDOR_GROUP = new VendorGroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VendorGroupRecord> getRecordType() {
        return VendorGroupRecord.class;
    }

    /**
     * The column <code>vendor_group.id</code>.
     */
    public final TableField<VendorGroupRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>vendor_group.status</code>.
     */
    public final TableField<VendorGroupRecord, Boolean> STATUS = createField(DSL.name("status"), SQLDataType.BIT, this, "");

    /**
     * The column <code>vendor_group.group_name</code>.
     */
    public final TableField<VendorGroupRecord, String> GROUP_NAME = createField(DSL.name("group_name"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>vendor_group.created_at</code>.
     */
    public final TableField<VendorGroupRecord, Long> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>vendor_group.created_by</code>.
     */
    public final TableField<VendorGroupRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>vendor_group.modified_at</code>.
     */
    public final TableField<VendorGroupRecord, Long> MODIFIED_AT = createField(DSL.name("modified_at"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>vendor_group.modified_by</code>.
     */
    public final TableField<VendorGroupRecord, String> MODIFIED_BY = createField(DSL.name("modified_by"), SQLDataType.VARCHAR(255), this, "");

    private VendorGroup(Name alias, Table<VendorGroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private VendorGroup(Name alias, Table<VendorGroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>vendor_group</code> table reference
     */
    public VendorGroup(String alias) {
        this(DSL.name(alias), VENDOR_GROUP);
    }

    /**
     * Create an aliased <code>vendor_group</code> table reference
     */
    public VendorGroup(Name alias) {
        this(alias, VENDOR_GROUP);
    }

    /**
     * Create a <code>vendor_group</code> table reference
     */
    public VendorGroup() {
        this(DSL.name("vendor_group"), null);
    }

    public <O extends Record> VendorGroup(Table<O> child, ForeignKey<O, VendorGroupRecord> key) {
        super(child, key, VENDOR_GROUP);
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<VendorGroupRecord, Long> getIdentity() {
        return (Identity<VendorGroupRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VendorGroupRecord> getPrimaryKey() {
        return Keys.KEY_VENDOR_GROUP_PRIMARY;
    }

    @Override
    public List<UniqueKey<VendorGroupRecord>> getKeys() {
        return Arrays.<UniqueKey<VendorGroupRecord>>asList(Keys.KEY_VENDOR_GROUP_PRIMARY, Keys.KEY_VENDOR_GROUP_UK_I326I2OORGGV96FHNS17SC721);
    }

    @Override
    public VendorGroup as(String alias) {
        return new VendorGroup(DSL.name(alias), this);
    }

    @Override
    public VendorGroup as(Name alias) {
        return new VendorGroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VendorGroup rename(String name) {
        return new VendorGroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VendorGroup rename(Name name) {
        return new VendorGroup(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Boolean, String, Long, String, Long, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
