/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq;


import com.neoin.shop.jooq.tables.Discount;
import com.neoin.shop.jooq.tables.Product;
import com.neoin.shop.jooq.tables.Vendor;
import com.neoin.shop.jooq.tables.VendorCategory;
import com.neoin.shop.jooq.tables.VendorCategoryMap;
import com.neoin.shop.jooq.tables.VendorGroup;
import com.neoin.shop.jooq.tables.records.DiscountRecord;
import com.neoin.shop.jooq.tables.records.ProductRecord;
import com.neoin.shop.jooq.tables.records.VendorCategoryMapRecord;
import com.neoin.shop.jooq.tables.records.VendorCategoryRecord;
import com.neoin.shop.jooq.tables.records.VendorGroupRecord;
import com.neoin.shop.jooq.tables.records.VendorRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DiscountRecord> KEY_DISCOUNT_PRIMARY = Internal.createUniqueKey(Discount.DISCOUNT, DSL.name("KEY_discount_PRIMARY"), new TableField[] { Discount.DISCOUNT.ID }, true);
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, DSL.name("KEY_product_PRIMARY"), new TableField[] { Product.PRODUCT.ID }, true);
    public static final UniqueKey<VendorRecord> KEY_VENDOR_PRIMARY = Internal.createUniqueKey(Vendor.VENDOR, DSL.name("KEY_vendor_PRIMARY"), new TableField[] { Vendor.VENDOR.ID }, true);
    public static final UniqueKey<VendorCategoryRecord> KEY_VENDOR_CATEGORY_PRIMARY = Internal.createUniqueKey(VendorCategory.VENDOR_CATEGORY, DSL.name("KEY_vendor_category_PRIMARY"), new TableField[] { VendorCategory.VENDOR_CATEGORY.ID }, true);
    public static final UniqueKey<VendorCategoryRecord> KEY_VENDOR_CATEGORY_UK_NPX9S9U8FP1A5CWCVO2F91DWV = Internal.createUniqueKey(VendorCategory.VENDOR_CATEGORY, DSL.name("KEY_vendor_category_UK_npx9s9u8fp1a5cwcvo2f91dwv"), new TableField[] { VendorCategory.VENDOR_CATEGORY.CATEGORY_NAME }, true);
    public static final UniqueKey<VendorCategoryMapRecord> KEY_VENDOR_CATEGORY_MAP_PRIMARY = Internal.createUniqueKey(VendorCategoryMap.VENDOR_CATEGORY_MAP, DSL.name("KEY_vendor_category_map_PRIMARY"), new TableField[] { VendorCategoryMap.VENDOR_CATEGORY_MAP.ID }, true);
    public static final UniqueKey<VendorGroupRecord> KEY_VENDOR_GROUP_PRIMARY = Internal.createUniqueKey(VendorGroup.VENDOR_GROUP, DSL.name("KEY_vendor_group_PRIMARY"), new TableField[] { VendorGroup.VENDOR_GROUP.ID }, true);
    public static final UniqueKey<VendorGroupRecord> KEY_VENDOR_GROUP_UK_I326I2OORGGV96FHNS17SC721 = Internal.createUniqueKey(VendorGroup.VENDOR_GROUP, DSL.name("KEY_vendor_group_UK_i326i2oorggv96fhns17sc721"), new TableField[] { VendorGroup.VENDOR_GROUP.GROUP_NAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<VendorRecord, VendorGroupRecord> FKAEW7PV6G3OY0RHF8HWMWDGO58 = Internal.createForeignKey(Vendor.VENDOR, DSL.name("FKaew7pv6g3oy0rhf8hwmwdgo58"), new TableField[] { Vendor.VENDOR.GROUP_ID }, Keys.KEY_VENDOR_GROUP_PRIMARY, new TableField[] { VendorGroup.VENDOR_GROUP.ID }, true);
}
