/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq;


import com.neoin.shop.jooq.tables.Discount;
import com.neoin.shop.jooq.tables.Product;
import com.neoin.shop.jooq.tables.Vendor;
import com.neoin.shop.jooq.tables.VendorCategory;
import com.neoin.shop.jooq.tables.VendorCategoryMap;
import com.neoin.shop.jooq.tables.VendorGroup;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>discount</code>.
     */
    public static final Discount DISCOUNT = Discount.DISCOUNT;

    /**
     * The table <code>product</code>.
     */
    public static final Product PRODUCT = Product.PRODUCT;

    /**
     * The table <code>vendor</code>.
     */
    public static final Vendor VENDOR = Vendor.VENDOR;

    /**
     * The table <code>vendor_category</code>.
     */
    public static final VendorCategory VENDOR_CATEGORY = VendorCategory.VENDOR_CATEGORY;

    /**
     * The table <code>vendor_category_map</code>.
     */
    public static final VendorCategoryMap VENDOR_CATEGORY_MAP = VendorCategoryMap.VENDOR_CATEGORY_MAP;

    /**
     * The table <code>vendor_group</code>.
     */
    public static final VendorGroup VENDOR_GROUP = VendorGroup.VENDOR_GROUP;
}
