/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq.tables.records;


import com.neoin.shop.jooq.tables.Discount;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DiscountRecord extends UpdatableRecordImpl<DiscountRecord> implements Record15<Long, Long, String, Long, String, String, Long, String, Long, Boolean, Long, String, Double, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>discount.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>discount.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>discount.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>discount.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>discount.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>discount.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>discount.modified_at</code>.
     */
    public void setModifiedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>discount.modified_at</code>.
     */
    public Long getModifiedAt() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>discount.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>discount.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>discount.category</code>.
     */
    public void setCategory(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>discount.category</code>.
     */
    public String getCategory() {
        return (String) get(5);
    }

    /**
     * Setter for <code>discount.from_date</code>.
     */
    public void setFromDate(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>discount.from_date</code>.
     */
    public Long getFromDate() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>discount.name</code>.
     */
    public void setName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>discount.name</code>.
     */
    public String getName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>discount.product_id</code>.
     */
    public void setProductId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>discount.product_id</code>.
     */
    public Long getProductId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>discount.status</code>.
     */
    public void setStatus(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>discount.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>discount.to_date</code>.
     */
    public void setToDate(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>discount.to_date</code>.
     */
    public Long getToDate() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>discount.type</code>.
     */
    public void setType(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>discount.type</code>.
     */
    public String getType() {
        return (String) get(11);
    }

    /**
     * Setter for <code>discount.value</code>.
     */
    public void setValue(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>discount.value</code>.
     */
    public Double getValue() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>discount.vendor_group_id</code>.
     */
    public void setVendorGroupId(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>discount.vendor_group_id</code>.
     */
    public Long getVendorGroupId() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>discount.vendor_id</code>.
     */
    public void setVendorId(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>discount.vendor_id</code>.
     */
    public Long getVendorId() {
        return (Long) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<Long, Long, String, Long, String, String, Long, String, Long, Boolean, Long, String, Double, Long, Long> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<Long, Long, String, Long, String, String, Long, String, Long, Boolean, Long, String, Double, Long, Long> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Discount.DISCOUNT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Discount.DISCOUNT.CREATED_AT;
    }

    @Override
    public Field<String> field3() {
        return Discount.DISCOUNT.CREATED_BY;
    }

    @Override
    public Field<Long> field4() {
        return Discount.DISCOUNT.MODIFIED_AT;
    }

    @Override
    public Field<String> field5() {
        return Discount.DISCOUNT.MODIFIED_BY;
    }

    @Override
    public Field<String> field6() {
        return Discount.DISCOUNT.CATEGORY;
    }

    @Override
    public Field<Long> field7() {
        return Discount.DISCOUNT.FROM_DATE;
    }

    @Override
    public Field<String> field8() {
        return Discount.DISCOUNT.NAME;
    }

    @Override
    public Field<Long> field9() {
        return Discount.DISCOUNT.PRODUCT_ID;
    }

    @Override
    public Field<Boolean> field10() {
        return Discount.DISCOUNT.STATUS;
    }

    @Override
    public Field<Long> field11() {
        return Discount.DISCOUNT.TO_DATE;
    }

    @Override
    public Field<String> field12() {
        return Discount.DISCOUNT.TYPE;
    }

    @Override
    public Field<Double> field13() {
        return Discount.DISCOUNT.VALUE;
    }

    @Override
    public Field<Long> field14() {
        return Discount.DISCOUNT.VENDOR_GROUP_ID;
    }

    @Override
    public Field<Long> field15() {
        return Discount.DISCOUNT.VENDOR_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatedAt();
    }

    @Override
    public String component3() {
        return getCreatedBy();
    }

    @Override
    public Long component4() {
        return getModifiedAt();
    }

    @Override
    public String component5() {
        return getModifiedBy();
    }

    @Override
    public String component6() {
        return getCategory();
    }

    @Override
    public Long component7() {
        return getFromDate();
    }

    @Override
    public String component8() {
        return getName();
    }

    @Override
    public Long component9() {
        return getProductId();
    }

    @Override
    public Boolean component10() {
        return getStatus();
    }

    @Override
    public Long component11() {
        return getToDate();
    }

    @Override
    public String component12() {
        return getType();
    }

    @Override
    public Double component13() {
        return getValue();
    }

    @Override
    public Long component14() {
        return getVendorGroupId();
    }

    @Override
    public Long component15() {
        return getVendorId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatedAt();
    }

    @Override
    public String value3() {
        return getCreatedBy();
    }

    @Override
    public Long value4() {
        return getModifiedAt();
    }

    @Override
    public String value5() {
        return getModifiedBy();
    }

    @Override
    public String value6() {
        return getCategory();
    }

    @Override
    public Long value7() {
        return getFromDate();
    }

    @Override
    public String value8() {
        return getName();
    }

    @Override
    public Long value9() {
        return getProductId();
    }

    @Override
    public Boolean value10() {
        return getStatus();
    }

    @Override
    public Long value11() {
        return getToDate();
    }

    @Override
    public String value12() {
        return getType();
    }

    @Override
    public Double value13() {
        return getValue();
    }

    @Override
    public Long value14() {
        return getVendorGroupId();
    }

    @Override
    public Long value15() {
        return getVendorId();
    }

    @Override
    public DiscountRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public DiscountRecord value2(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public DiscountRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public DiscountRecord value4(Long value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public DiscountRecord value5(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public DiscountRecord value6(String value) {
        setCategory(value);
        return this;
    }

    @Override
    public DiscountRecord value7(Long value) {
        setFromDate(value);
        return this;
    }

    @Override
    public DiscountRecord value8(String value) {
        setName(value);
        return this;
    }

    @Override
    public DiscountRecord value9(Long value) {
        setProductId(value);
        return this;
    }

    @Override
    public DiscountRecord value10(Boolean value) {
        setStatus(value);
        return this;
    }

    @Override
    public DiscountRecord value11(Long value) {
        setToDate(value);
        return this;
    }

    @Override
    public DiscountRecord value12(String value) {
        setType(value);
        return this;
    }

    @Override
    public DiscountRecord value13(Double value) {
        setValue(value);
        return this;
    }

    @Override
    public DiscountRecord value14(Long value) {
        setVendorGroupId(value);
        return this;
    }

    @Override
    public DiscountRecord value15(Long value) {
        setVendorId(value);
        return this;
    }

    @Override
    public DiscountRecord values(Long value1, Long value2, String value3, Long value4, String value5, String value6, Long value7, String value8, Long value9, Boolean value10, Long value11, String value12, Double value13, Long value14, Long value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DiscountRecord
     */
    public DiscountRecord() {
        super(Discount.DISCOUNT);
    }

    /**
     * Create a detached, initialised DiscountRecord
     */
    public DiscountRecord(Long id, Long createdAt, String createdBy, Long modifiedAt, String modifiedBy, String category, Long fromDate, String name, Long productId, Boolean status, Long toDate, String type, Double value, Long vendorGroupId, Long vendorId) {
        super(Discount.DISCOUNT);

        setId(id);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
        setCategory(category);
        setFromDate(fromDate);
        setName(name);
        setProductId(productId);
        setStatus(status);
        setToDate(toDate);
        setType(type);
        setValue(value);
        setVendorGroupId(vendorGroupId);
        setVendorId(vendorId);
    }
}
