/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq.tables.records;


import com.neoin.shop.jooq.tables.Product;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record19<Long, Long, String, Long, String, Long, Long, String, String, String, String, Double, Long, String, Boolean, String, String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>product.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>product.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>product.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>product.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>product.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>product.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>product.modified_at</code>.
     */
    public void setModifiedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>product.modified_at</code>.
     */
    public Long getModifiedAt() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>product.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>product.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>product.discount_id</code>.
     */
    public void setDiscountId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>product.discount_id</code>.
     */
    public Long getDiscountId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>product.product_category_id</code>.
     */
    public void setProductCategoryId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>product.product_category_id</code>.
     */
    public Long getProductCategoryId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>product.product_image</code>.
     */
    public void setProductImage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>product.product_image</code>.
     */
    public String getProductImage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>product.product_long_desc</code>.
     */
    public void setProductLongDesc(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>product.product_long_desc</code>.
     */
    public String getProductLongDesc() {
        return (String) get(8);
    }

    /**
     * Setter for <code>product.product_manufacturer</code>.
     */
    public void setProductManufacturer(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>product.product_manufacturer</code>.
     */
    public String getProductManufacturer() {
        return (String) get(9);
    }

    /**
     * Setter for <code>product.product_name</code>.
     */
    public void setProductName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>product.product_name</code>.
     */
    public String getProductName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>product.product_price</code>.
     */
    public void setProductPrice(Double value) {
        set(11, value);
    }

    /**
     * Getter for <code>product.product_price</code>.
     */
    public Double getProductPrice() {
        return (Double) get(11);
    }

    /**
     * Setter for <code>product.product_sku</code>.
     */
    public void setProductSku(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>product.product_sku</code>.
     */
    public Long getProductSku() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>product.product_short_desc</code>.
     */
    public void setProductShortDesc(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>product.product_short_desc</code>.
     */
    public String getProductShortDesc() {
        return (String) get(13);
    }

    /**
     * Setter for <code>product.product_status</code>.
     */
    public void setProductStatus(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>product.product_status</code>.
     */
    public Boolean getProductStatus() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>product.product_thumb</code>.
     */
    public void setProductThumb(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>product.product_thumb</code>.
     */
    public String getProductThumb() {
        return (String) get(15);
    }

    /**
     * Setter for <code>product.product_type</code>.
     */
    public void setProductType(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>product.product_type</code>.
     */
    public String getProductType() {
        return (String) get(16);
    }

    /**
     * Setter for <code>product.product_updated_date</code>.
     */
    public void setProductUpdatedDate(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>product.product_updated_date</code>.
     */
    public Long getProductUpdatedDate() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>product.vendor_id</code>.
     */
    public void setVendorId(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>product.vendor_id</code>.
     */
    public Long getVendorId() {
        return (Long) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, Long, String, Long, String, Long, Long, String, String, String, String, Double, Long, String, Boolean, String, String, Long, Long> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, Long, String, Long, String, Long, Long, String, String, String, String, Double, Long, String, Boolean, String, String, Long, Long> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Product.PRODUCT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Product.PRODUCT.CREATED_AT;
    }

    @Override
    public Field<String> field3() {
        return Product.PRODUCT.CREATED_BY;
    }

    @Override
    public Field<Long> field4() {
        return Product.PRODUCT.MODIFIED_AT;
    }

    @Override
    public Field<String> field5() {
        return Product.PRODUCT.MODIFIED_BY;
    }

    @Override
    public Field<Long> field6() {
        return Product.PRODUCT.DISCOUNT_ID;
    }

    @Override
    public Field<Long> field7() {
        return Product.PRODUCT.PRODUCT_CATEGORY_ID;
    }

    @Override
    public Field<String> field8() {
        return Product.PRODUCT.PRODUCT_IMAGE;
    }

    @Override
    public Field<String> field9() {
        return Product.PRODUCT.PRODUCT_LONG_DESC;
    }

    @Override
    public Field<String> field10() {
        return Product.PRODUCT.PRODUCT_MANUFACTURER;
    }

    @Override
    public Field<String> field11() {
        return Product.PRODUCT.PRODUCT_NAME;
    }

    @Override
    public Field<Double> field12() {
        return Product.PRODUCT.PRODUCT_PRICE;
    }

    @Override
    public Field<Long> field13() {
        return Product.PRODUCT.PRODUCT_SKU;
    }

    @Override
    public Field<String> field14() {
        return Product.PRODUCT.PRODUCT_SHORT_DESC;
    }

    @Override
    public Field<Boolean> field15() {
        return Product.PRODUCT.PRODUCT_STATUS;
    }

    @Override
    public Field<String> field16() {
        return Product.PRODUCT.PRODUCT_THUMB;
    }

    @Override
    public Field<String> field17() {
        return Product.PRODUCT.PRODUCT_TYPE;
    }

    @Override
    public Field<Long> field18() {
        return Product.PRODUCT.PRODUCT_UPDATED_DATE;
    }

    @Override
    public Field<Long> field19() {
        return Product.PRODUCT.VENDOR_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatedAt();
    }

    @Override
    public String component3() {
        return getCreatedBy();
    }

    @Override
    public Long component4() {
        return getModifiedAt();
    }

    @Override
    public String component5() {
        return getModifiedBy();
    }

    @Override
    public Long component6() {
        return getDiscountId();
    }

    @Override
    public Long component7() {
        return getProductCategoryId();
    }

    @Override
    public String component8() {
        return getProductImage();
    }

    @Override
    public String component9() {
        return getProductLongDesc();
    }

    @Override
    public String component10() {
        return getProductManufacturer();
    }

    @Override
    public String component11() {
        return getProductName();
    }

    @Override
    public Double component12() {
        return getProductPrice();
    }

    @Override
    public Long component13() {
        return getProductSku();
    }

    @Override
    public String component14() {
        return getProductShortDesc();
    }

    @Override
    public Boolean component15() {
        return getProductStatus();
    }

    @Override
    public String component16() {
        return getProductThumb();
    }

    @Override
    public String component17() {
        return getProductType();
    }

    @Override
    public Long component18() {
        return getProductUpdatedDate();
    }

    @Override
    public Long component19() {
        return getVendorId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatedAt();
    }

    @Override
    public String value3() {
        return getCreatedBy();
    }

    @Override
    public Long value4() {
        return getModifiedAt();
    }

    @Override
    public String value5() {
        return getModifiedBy();
    }

    @Override
    public Long value6() {
        return getDiscountId();
    }

    @Override
    public Long value7() {
        return getProductCategoryId();
    }

    @Override
    public String value8() {
        return getProductImage();
    }

    @Override
    public String value9() {
        return getProductLongDesc();
    }

    @Override
    public String value10() {
        return getProductManufacturer();
    }

    @Override
    public String value11() {
        return getProductName();
    }

    @Override
    public Double value12() {
        return getProductPrice();
    }

    @Override
    public Long value13() {
        return getProductSku();
    }

    @Override
    public String value14() {
        return getProductShortDesc();
    }

    @Override
    public Boolean value15() {
        return getProductStatus();
    }

    @Override
    public String value16() {
        return getProductThumb();
    }

    @Override
    public String value17() {
        return getProductType();
    }

    @Override
    public Long value18() {
        return getProductUpdatedDate();
    }

    @Override
    public Long value19() {
        return getVendorId();
    }

    @Override
    public ProductRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProductRecord value2(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ProductRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public ProductRecord value4(Long value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public ProductRecord value5(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public ProductRecord value6(Long value) {
        setDiscountId(value);
        return this;
    }

    @Override
    public ProductRecord value7(Long value) {
        setProductCategoryId(value);
        return this;
    }

    @Override
    public ProductRecord value8(String value) {
        setProductImage(value);
        return this;
    }

    @Override
    public ProductRecord value9(String value) {
        setProductLongDesc(value);
        return this;
    }

    @Override
    public ProductRecord value10(String value) {
        setProductManufacturer(value);
        return this;
    }

    @Override
    public ProductRecord value11(String value) {
        setProductName(value);
        return this;
    }

    @Override
    public ProductRecord value12(Double value) {
        setProductPrice(value);
        return this;
    }

    @Override
    public ProductRecord value13(Long value) {
        setProductSku(value);
        return this;
    }

    @Override
    public ProductRecord value14(String value) {
        setProductShortDesc(value);
        return this;
    }

    @Override
    public ProductRecord value15(Boolean value) {
        setProductStatus(value);
        return this;
    }

    @Override
    public ProductRecord value16(String value) {
        setProductThumb(value);
        return this;
    }

    @Override
    public ProductRecord value17(String value) {
        setProductType(value);
        return this;
    }

    @Override
    public ProductRecord value18(Long value) {
        setProductUpdatedDate(value);
        return this;
    }

    @Override
    public ProductRecord value19(Long value) {
        setVendorId(value);
        return this;
    }

    @Override
    public ProductRecord values(Long value1, Long value2, String value3, Long value4, String value5, Long value6, Long value7, String value8, String value9, String value10, String value11, Double value12, Long value13, String value14, Boolean value15, String value16, String value17, Long value18, Long value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Long id, Long createdAt, String createdBy, Long modifiedAt, String modifiedBy, Long discountId, Long productCategoryId, String productImage, String productLongDesc, String productManufacturer, String productName, Double productPrice, Long productSku, String productShortDesc, Boolean productStatus, String productThumb, String productType, Long productUpdatedDate, Long vendorId) {
        super(Product.PRODUCT);

        setId(id);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
        setDiscountId(discountId);
        setProductCategoryId(productCategoryId);
        setProductImage(productImage);
        setProductLongDesc(productLongDesc);
        setProductManufacturer(productManufacturer);
        setProductName(productName);
        setProductPrice(productPrice);
        setProductSku(productSku);
        setProductShortDesc(productShortDesc);
        setProductStatus(productStatus);
        setProductThumb(productThumb);
        setProductType(productType);
        setProductUpdatedDate(productUpdatedDate);
        setVendorId(vendorId);
    }
}
