/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq.tables.records;


import com.neoin.shop.jooq.tables.VendorGroup;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorGroupRecord extends UpdatableRecordImpl<VendorGroupRecord> implements Record7<Long, Boolean, String, Long, String, Long, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>vendor_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>vendor_group.status</code>.
     */
    public void setStatus(Boolean value) {
        set(1, value);
    }

    /**
     * Getter for <code>vendor_group.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(1);
    }

    /**
     * Setter for <code>vendor_group.group_name</code>.
     */
    public void setGroupName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vendor_group.group_name</code>.
     */
    public String getGroupName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_group.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>vendor_group.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>vendor_group.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vendor_group.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_group.modified_at</code>.
     */
    public void setModifiedAt(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>vendor_group.modified_at</code>.
     */
    public Long getModifiedAt() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>vendor_group.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>vendor_group.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Boolean, String, Long, String, Long, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Boolean, String, Long, String, Long, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return VendorGroup.VENDOR_GROUP.ID;
    }

    @Override
    public Field<Boolean> field2() {
        return VendorGroup.VENDOR_GROUP.STATUS;
    }

    @Override
    public Field<String> field3() {
        return VendorGroup.VENDOR_GROUP.GROUP_NAME;
    }

    @Override
    public Field<Long> field4() {
        return VendorGroup.VENDOR_GROUP.CREATED_AT;
    }

    @Override
    public Field<String> field5() {
        return VendorGroup.VENDOR_GROUP.CREATED_BY;
    }

    @Override
    public Field<Long> field6() {
        return VendorGroup.VENDOR_GROUP.MODIFIED_AT;
    }

    @Override
    public Field<String> field7() {
        return VendorGroup.VENDOR_GROUP.MODIFIED_BY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Boolean component2() {
        return getStatus();
    }

    @Override
    public String component3() {
        return getGroupName();
    }

    @Override
    public Long component4() {
        return getCreatedAt();
    }

    @Override
    public String component5() {
        return getCreatedBy();
    }

    @Override
    public Long component6() {
        return getModifiedAt();
    }

    @Override
    public String component7() {
        return getModifiedBy();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Boolean value2() {
        return getStatus();
    }

    @Override
    public String value3() {
        return getGroupName();
    }

    @Override
    public Long value4() {
        return getCreatedAt();
    }

    @Override
    public String value5() {
        return getCreatedBy();
    }

    @Override
    public Long value6() {
        return getModifiedAt();
    }

    @Override
    public String value7() {
        return getModifiedBy();
    }

    @Override
    public VendorGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VendorGroupRecord value2(Boolean value) {
        setStatus(value);
        return this;
    }

    @Override
    public VendorGroupRecord value3(String value) {
        setGroupName(value);
        return this;
    }

    @Override
    public VendorGroupRecord value4(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VendorGroupRecord value5(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public VendorGroupRecord value6(Long value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public VendorGroupRecord value7(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public VendorGroupRecord values(Long value1, Boolean value2, String value3, Long value4, String value5, Long value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendorGroupRecord
     */
    public VendorGroupRecord() {
        super(VendorGroup.VENDOR_GROUP);
    }

    /**
     * Create a detached, initialised VendorGroupRecord
     */
    public VendorGroupRecord(Long id, Boolean status, String groupName, Long createdAt, String createdBy, Long modifiedAt, String modifiedBy) {
        super(VendorGroup.VENDOR_GROUP);

        setId(id);
        setStatus(status);
        setGroupName(groupName);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
    }
}
