/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq.tables.records;


import com.neoin.shop.jooq.tables.VendorCategory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorCategoryRecord extends UpdatableRecordImpl<VendorCategoryRecord> implements Record8<Long, Long, String, Long, String, Boolean, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor_category.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>vendor_category.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>vendor_category.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>vendor_category.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>vendor_category.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vendor_category.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor_category.modified_at</code>.
     */
    public void setModifiedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>vendor_category.modified_at</code>.
     */
    public Long getModifiedAt() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>vendor_category.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vendor_category.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor_category.status</code>.
     */
    public void setStatus(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>vendor_category.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>vendor_category.category_name</code>.
     */
    public void setCategoryName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>vendor_category.category_name</code>.
     */
    public String getCategoryName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor_category.priority</code>.
     */
    public void setPriority(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>vendor_category.priority</code>.
     */
    public Integer getPriority() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, Long, String, Boolean, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, String, Long, String, Boolean, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return VendorCategory.VENDOR_CATEGORY.ID;
    }

    @Override
    public Field<Long> field2() {
        return VendorCategory.VENDOR_CATEGORY.CREATED_AT;
    }

    @Override
    public Field<String> field3() {
        return VendorCategory.VENDOR_CATEGORY.CREATED_BY;
    }

    @Override
    public Field<Long> field4() {
        return VendorCategory.VENDOR_CATEGORY.MODIFIED_AT;
    }

    @Override
    public Field<String> field5() {
        return VendorCategory.VENDOR_CATEGORY.MODIFIED_BY;
    }

    @Override
    public Field<Boolean> field6() {
        return VendorCategory.VENDOR_CATEGORY.STATUS;
    }

    @Override
    public Field<String> field7() {
        return VendorCategory.VENDOR_CATEGORY.CATEGORY_NAME;
    }

    @Override
    public Field<Integer> field8() {
        return VendorCategory.VENDOR_CATEGORY.PRIORITY;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatedAt();
    }

    @Override
    public String component3() {
        return getCreatedBy();
    }

    @Override
    public Long component4() {
        return getModifiedAt();
    }

    @Override
    public String component5() {
        return getModifiedBy();
    }

    @Override
    public Boolean component6() {
        return getStatus();
    }

    @Override
    public String component7() {
        return getCategoryName();
    }

    @Override
    public Integer component8() {
        return getPriority();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatedAt();
    }

    @Override
    public String value3() {
        return getCreatedBy();
    }

    @Override
    public Long value4() {
        return getModifiedAt();
    }

    @Override
    public String value5() {
        return getModifiedBy();
    }

    @Override
    public Boolean value6() {
        return getStatus();
    }

    @Override
    public String value7() {
        return getCategoryName();
    }

    @Override
    public Integer value8() {
        return getPriority();
    }

    @Override
    public VendorCategoryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VendorCategoryRecord value2(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VendorCategoryRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public VendorCategoryRecord value4(Long value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public VendorCategoryRecord value5(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public VendorCategoryRecord value6(Boolean value) {
        setStatus(value);
        return this;
    }

    @Override
    public VendorCategoryRecord value7(String value) {
        setCategoryName(value);
        return this;
    }

    @Override
    public VendorCategoryRecord value8(Integer value) {
        setPriority(value);
        return this;
    }

    @Override
    public VendorCategoryRecord values(Long value1, Long value2, String value3, Long value4, String value5, Boolean value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendorCategoryRecord
     */
    public VendorCategoryRecord() {
        super(VendorCategory.VENDOR_CATEGORY);
    }

    /**
     * Create a detached, initialised VendorCategoryRecord
     */
    public VendorCategoryRecord(Long id, Long createdAt, String createdBy, Long modifiedAt, String modifiedBy, Boolean status, String categoryName, Integer priority) {
        super(VendorCategory.VENDOR_CATEGORY);

        setId(id);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
        setStatus(status);
        setCategoryName(categoryName);
        setPriority(priority);
    }
}
