/*
 * This file is generated by jOOQ.
 */
package com.neoin.shop.jooq.tables.records;


import com.neoin.shop.jooq.tables.Vendor;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VendorRecord extends UpdatableRecordImpl<VendorRecord> implements Record22<Long, Long, String, Long, String, String, String, String, String, String, String, String, String, Double, String, Double, String, String, String, Boolean, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>vendor.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>vendor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>vendor.created_at</code>.
     */
    public void setCreatedAt(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>vendor.created_at</code>.
     */
    public Long getCreatedAt() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>vendor.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>vendor.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>vendor.modified_at</code>.
     */
    public void setModifiedAt(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>vendor.modified_at</code>.
     */
    public Long getModifiedAt() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>vendor.modified_by</code>.
     */
    public void setModifiedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>vendor.modified_by</code>.
     */
    public String getModifiedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>vendor.address1</code>.
     */
    public void setAddress1(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>vendor.address1</code>.
     */
    public String getAddress1() {
        return (String) get(5);
    }

    /**
     * Setter for <code>vendor.address2</code>.
     */
    public void setAddress2(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>vendor.address2</code>.
     */
    public String getAddress2() {
        return (String) get(6);
    }

    /**
     * Setter for <code>vendor.area</code>.
     */
    public void setArea(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>vendor.area</code>.
     */
    public String getArea() {
        return (String) get(7);
    }

    /**
     * Setter for <code>vendor.city</code>.
     */
    public void setCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>vendor.city</code>.
     */
    public String getCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>vendor.code</code>.
     */
    public void setCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>vendor.code</code>.
     */
    public String getCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>vendor.country</code>.
     */
    public void setCountry(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>vendor.country</code>.
     */
    public String getCountry() {
        return (String) get(10);
    }

    /**
     * Setter for <code>vendor.image</code>.
     */
    public void setImage(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>vendor.image</code>.
     */
    public String getImage() {
        return (String) get(11);
    }

    /**
     * Setter for <code>vendor.land_mark</code>.
     */
    public void setLandMark(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>vendor.land_mark</code>.
     */
    public String getLandMark() {
        return (String) get(12);
    }

    /**
     * Setter for <code>vendor.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>vendor.latitude</code>.
     */
    public Double getLatitude() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>vendor.long_desc</code>.
     */
    public void setLongDesc(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>vendor.long_desc</code>.
     */
    public String getLongDesc() {
        return (String) get(14);
    }

    /**
     * Setter for <code>vendor.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(15, value);
    }

    /**
     * Getter for <code>vendor.longitude</code>.
     */
    public Double getLongitude() {
        return (Double) get(15);
    }

    /**
     * Setter for <code>vendor.name</code>.
     */
    public void setName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>vendor.name</code>.
     */
    public String getName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>vendor.short_desc</code>.
     */
    public void setShortDesc(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>vendor.short_desc</code>.
     */
    public String getShortDesc() {
        return (String) get(17);
    }

    /**
     * Setter for <code>vendor.state</code>.
     */
    public void setState(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>vendor.state</code>.
     */
    public String getState() {
        return (String) get(18);
    }

    /**
     * Setter for <code>vendor.status</code>.
     */
    public void setStatus(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>vendor.status</code>.
     */
    public Boolean getStatus() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>vendor.thumb</code>.
     */
    public void setThumb(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>vendor.thumb</code>.
     */
    public String getThumb() {
        return (String) get(20);
    }

    /**
     * Setter for <code>vendor.group_id</code>.
     */
    public void setGroupId(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>vendor.group_id</code>.
     */
    public Long getGroupId() {
        return (Long) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row22<Long, Long, String, Long, String, String, String, String, String, String, String, String, String, Double, String, Double, String, String, String, Boolean, String, Long> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    @Override
    public Row22<Long, Long, String, Long, String, String, String, String, String, String, String, String, String, Double, String, Double, String, String, String, Boolean, String, Long> valuesRow() {
        return (Row22) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Vendor.VENDOR.ID;
    }

    @Override
    public Field<Long> field2() {
        return Vendor.VENDOR.CREATED_AT;
    }

    @Override
    public Field<String> field3() {
        return Vendor.VENDOR.CREATED_BY;
    }

    @Override
    public Field<Long> field4() {
        return Vendor.VENDOR.MODIFIED_AT;
    }

    @Override
    public Field<String> field5() {
        return Vendor.VENDOR.MODIFIED_BY;
    }

    @Override
    public Field<String> field6() {
        return Vendor.VENDOR.ADDRESS1;
    }

    @Override
    public Field<String> field7() {
        return Vendor.VENDOR.ADDRESS2;
    }

    @Override
    public Field<String> field8() {
        return Vendor.VENDOR.AREA;
    }

    @Override
    public Field<String> field9() {
        return Vendor.VENDOR.CITY;
    }

    @Override
    public Field<String> field10() {
        return Vendor.VENDOR.CODE;
    }

    @Override
    public Field<String> field11() {
        return Vendor.VENDOR.COUNTRY;
    }

    @Override
    public Field<String> field12() {
        return Vendor.VENDOR.IMAGE;
    }

    @Override
    public Field<String> field13() {
        return Vendor.VENDOR.LAND_MARK;
    }

    @Override
    public Field<Double> field14() {
        return Vendor.VENDOR.LATITUDE;
    }

    @Override
    public Field<String> field15() {
        return Vendor.VENDOR.LONG_DESC;
    }

    @Override
    public Field<Double> field16() {
        return Vendor.VENDOR.LONGITUDE;
    }

    @Override
    public Field<String> field17() {
        return Vendor.VENDOR.NAME;
    }

    @Override
    public Field<String> field18() {
        return Vendor.VENDOR.SHORT_DESC;
    }

    @Override
    public Field<String> field19() {
        return Vendor.VENDOR.STATE;
    }

    @Override
    public Field<Boolean> field20() {
        return Vendor.VENDOR.STATUS;
    }

    @Override
    public Field<String> field21() {
        return Vendor.VENDOR.THUMB;
    }

    @Override
    public Field<Long> field22() {
        return Vendor.VENDOR.GROUP_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCreatedAt();
    }

    @Override
    public String component3() {
        return getCreatedBy();
    }

    @Override
    public Long component4() {
        return getModifiedAt();
    }

    @Override
    public String component5() {
        return getModifiedBy();
    }

    @Override
    public String component6() {
        return getAddress1();
    }

    @Override
    public String component7() {
        return getAddress2();
    }

    @Override
    public String component8() {
        return getArea();
    }

    @Override
    public String component9() {
        return getCity();
    }

    @Override
    public String component10() {
        return getCode();
    }

    @Override
    public String component11() {
        return getCountry();
    }

    @Override
    public String component12() {
        return getImage();
    }

    @Override
    public String component13() {
        return getLandMark();
    }

    @Override
    public Double component14() {
        return getLatitude();
    }

    @Override
    public String component15() {
        return getLongDesc();
    }

    @Override
    public Double component16() {
        return getLongitude();
    }

    @Override
    public String component17() {
        return getName();
    }

    @Override
    public String component18() {
        return getShortDesc();
    }

    @Override
    public String component19() {
        return getState();
    }

    @Override
    public Boolean component20() {
        return getStatus();
    }

    @Override
    public String component21() {
        return getThumb();
    }

    @Override
    public Long component22() {
        return getGroupId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCreatedAt();
    }

    @Override
    public String value3() {
        return getCreatedBy();
    }

    @Override
    public Long value4() {
        return getModifiedAt();
    }

    @Override
    public String value5() {
        return getModifiedBy();
    }

    @Override
    public String value6() {
        return getAddress1();
    }

    @Override
    public String value7() {
        return getAddress2();
    }

    @Override
    public String value8() {
        return getArea();
    }

    @Override
    public String value9() {
        return getCity();
    }

    @Override
    public String value10() {
        return getCode();
    }

    @Override
    public String value11() {
        return getCountry();
    }

    @Override
    public String value12() {
        return getImage();
    }

    @Override
    public String value13() {
        return getLandMark();
    }

    @Override
    public Double value14() {
        return getLatitude();
    }

    @Override
    public String value15() {
        return getLongDesc();
    }

    @Override
    public Double value16() {
        return getLongitude();
    }

    @Override
    public String value17() {
        return getName();
    }

    @Override
    public String value18() {
        return getShortDesc();
    }

    @Override
    public String value19() {
        return getState();
    }

    @Override
    public Boolean value20() {
        return getStatus();
    }

    @Override
    public String value21() {
        return getThumb();
    }

    @Override
    public Long value22() {
        return getGroupId();
    }

    @Override
    public VendorRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public VendorRecord value2(Long value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public VendorRecord value3(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public VendorRecord value4(Long value) {
        setModifiedAt(value);
        return this;
    }

    @Override
    public VendorRecord value5(String value) {
        setModifiedBy(value);
        return this;
    }

    @Override
    public VendorRecord value6(String value) {
        setAddress1(value);
        return this;
    }

    @Override
    public VendorRecord value7(String value) {
        setAddress2(value);
        return this;
    }

    @Override
    public VendorRecord value8(String value) {
        setArea(value);
        return this;
    }

    @Override
    public VendorRecord value9(String value) {
        setCity(value);
        return this;
    }

    @Override
    public VendorRecord value10(String value) {
        setCode(value);
        return this;
    }

    @Override
    public VendorRecord value11(String value) {
        setCountry(value);
        return this;
    }

    @Override
    public VendorRecord value12(String value) {
        setImage(value);
        return this;
    }

    @Override
    public VendorRecord value13(String value) {
        setLandMark(value);
        return this;
    }

    @Override
    public VendorRecord value14(Double value) {
        setLatitude(value);
        return this;
    }

    @Override
    public VendorRecord value15(String value) {
        setLongDesc(value);
        return this;
    }

    @Override
    public VendorRecord value16(Double value) {
        setLongitude(value);
        return this;
    }

    @Override
    public VendorRecord value17(String value) {
        setName(value);
        return this;
    }

    @Override
    public VendorRecord value18(String value) {
        setShortDesc(value);
        return this;
    }

    @Override
    public VendorRecord value19(String value) {
        setState(value);
        return this;
    }

    @Override
    public VendorRecord value20(Boolean value) {
        setStatus(value);
        return this;
    }

    @Override
    public VendorRecord value21(String value) {
        setThumb(value);
        return this;
    }

    @Override
    public VendorRecord value22(Long value) {
        setGroupId(value);
        return this;
    }

    @Override
    public VendorRecord values(Long value1, Long value2, String value3, Long value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, Double value14, String value15, Double value16, String value17, String value18, String value19, Boolean value20, String value21, Long value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VendorRecord
     */
    public VendorRecord() {
        super(Vendor.VENDOR);
    }

    /**
     * Create a detached, initialised VendorRecord
     */
    public VendorRecord(Long id, Long createdAt, String createdBy, Long modifiedAt, String modifiedBy, String address1, String address2, String area, String city, String code, String country, String image, String landMark, Double latitude, String longDesc, Double longitude, String name, String shortDesc, String state, Boolean status, String thumb, Long groupId) {
        super(Vendor.VENDOR);

        setId(id);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setModifiedAt(modifiedAt);
        setModifiedBy(modifiedBy);
        setAddress1(address1);
        setAddress2(address2);
        setArea(area);
        setCity(city);
        setCode(code);
        setCountry(country);
        setImage(image);
        setLandMark(landMark);
        setLatitude(latitude);
        setLongDesc(longDesc);
        setLongitude(longitude);
        setName(name);
        setShortDesc(shortDesc);
        setState(state);
        setStatus(status);
        setThumb(thumb);
        setGroupId(groupId);
    }
}
