spring:
  application:
    name: neoin-eureka-server
  config:
    import: configserver:http://cloud-config-server:8888/config?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100
  cloud:
    config:
      label: main

