FROM openjdk:11.0.7-jre-slim-buster
MAINTAINER manjunath.melavanki
COPY build/libs/neoin-cloud-config-server-0.0.1.jar cloud-config-server-1.0.0.jar
ENTRYPOINT ["java","-jar","/cloud-config-server-1.0.0.jar"]